name: learn-github-actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-nodejs-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Check NodeJS version
        run: npm --version

      - name: Install Express
        run: npm install -g express

      - name: List all dependencies
        run: npm ls
